### ISSUE TITLE
Cannot Map Host Audio Into Container Correctly

### ISSUE THREAD

**Issue by epoch-philosophy** [zelikos/davincibox#105]
This may be a confusing one to troubleshoot as everybody's host audio setup will be different. I am currently using Pipewire and Wireplumber (on Fedora 40) and am using a MOTU Ultralite Mk5 as an audio interface for my inputs and outputs.

My Davinci Resolve in the distrobox is only mapping ALSA inputs and outputs as shown in Fairlight here:
![Screenshot from 2024-07-12 14-55-29](https://github.com/user-attachments/assets/146a893f-181e-4b3d-ba30-2f3ff21bfe89)

I essentially have zero audio in the Davincibox container. I though there may be some missing packages in the container, but haven't found anything that would remedy the issue. I would imagine Alsa is the main audio source present inside the container for stability reasons. As I know Davinci has had some issues with Pipewire historically. 

Another idea is that perhaps certain ENV variables that should be passed, such as the hosts audio, (which I think may not be present due to stability issues) might be something that should be explored. Or my system is just not allowing my host audio to interact with the container correctly. I am familiar with container deployment through YAML, and since this is configured with Bash scripting and some container creation processes I am not familiar with, I am a little stuck nor know where to start. While I am good with most things Docker, Podman, etc. as in deployment goes, (I have a home server) I am sadly unfamiliar with creating containers themselves as a development process.

Any idea what might be causing this?

**Comment by zelikos** [comment]
I can confirm that, on my end, Davinci in davincibox does use ALSA as the audio source. In my case, audio output is working just fine, but input doesn't seem to be. We've had issues related to audio reported before where adding missing packages did fix things, but I'm not sure whether or not missing packages are the problem here.

Are you able to test this with DaVinci Resolve installed normally, without davincibox? I'd be curious to see what the Patch Input/Output shows that way.

**Comment by epoch-philosophy** [comment]
Yup. So, I decided to try and rebuild Davinci in a distrobox manually and was able to get the output to work perfectly fine, that said, my input *also* worked, but sounded horrendous. No idea as to why.

I then decided to try and install on my base Fedora OS. I can now get audio through the output, but zero audio through my input.

I am guessing there's an issue with how Wireplumber, Pipewire, Pipewire-Pulse, may be working with Alsa to be honest.

**Comment by zelikos** [comment]
Yeah, this is sounding more like an issue either with Pipewire/Wireplumber working with ALSA, or with DaVinci Resolve's handling of audio on Linux, than it sounds like an issue specific to davincibox.

Closing for now, but on the off chance there's anything that *can* be done about it in davincibox, this can always be re-opened in the future.

**Comment by epoch-philosophy** [comment]
Gotcha. If you get the chance and get your inputs working, I'd def love to know! So far I can only really use Audacity for recording on here. Fairlight rules and I'd definitely prefer to use it.

**Comment by SolidTux** [comment]
I was able to get recording to work (with info from [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2870)) by putting

```
pcm.!default {
    type pulse
}
```

into `.asoundrc` (probably could be done global in the container, but I'm not sure if this will break it on other distros, I'm running everything on Fedora 41). But, this also required installing `alsa-plugins-pulseaudio` in the container.
