### ISSUE TITLE
Resolve doesn't scale correctly to the workspace, and is lacking basic controlls (I cannot move it around, minimise, maximise, etc.)

### ISSUE THREAD

**Issue by 2019Z2** [zelikos/davincibox#111]
**IMPORTANT**

Before reporting a bug, make sure that you can reproduce it on the latest version of davincibox.
Install Resolve, Launch it.
See the [upgrading](https://github.com/zelikos/davincibox#upgrading) section of the README for more information.
-- Done --

**Describe the bug**

It's not possible to move the program around across the desktop, or to control it from within the desktop - no header is available, as if my desktop environment, gnome, doesn't know how to handle the window.

**Installation method used**

- [ *] `setup.sh`
- Manual
  - [ ] Distrobox
  - [* ] Toolbox (Shipped by default)

**To Reproduce**

Steps to reproduce the behaviour:
1. Open Resolve
2. Open ANY project you happen to have
3. See error

**Expected behaviour**

The main editor window should have  been detected by the desktop and some sort have header would be attached. I could've move the window around, resize it, minimise, maximise, and control it to my heart's content.

**Screenshots**

**System information (please complete the following)**

 - Distro: Fedora 40 Workstation Edition
 - Desktop Environment: Gnome 46
 - GPU: Intel Graphics  ((RPL-S) embedded inside 13th gen core i-7)
 
**Additional context**
I may add this later, if i find out something related

**Comment by 2019Z2** [comment]
I am using extensions, BUT this never affected any other apps.

**Comment by zelikos** [comment]
Not an issue with davincibox, this happens with Resolve on Wayland when installed directly on the host OS too.

**Comment by 2019Z2** [comment]
X11 is also affected.
here's an example - it's like an immovable object has spawned on my screen:
![תמונה](https://github.com/user-attachments/assets/1b657e20-4356-45f0-b794-3b164fc27032)

**Comment by 2019Z2** [comment]
It's also unstable - my system keeps detecting it as not responding - whilst it is responding very well, and the only remedy is to force close it because fedora is annoying.

**Comment by zelikos** [comment]
> X11 is also affected. here's an example - it's like an immovable object has spawned on my screen: ![תמונה](https://private-user-images.githubusercontent.com/79469120/356549931-1b657e20-4356-45f0-b794-3b164fc27032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMTEyODgsIm5iZiI6MTcyMzIxMDk4OCwicGF0aCI6Ii83OTQ2OTEyMC8zNTY1NDk5MzEtMWI2NTdlMjAtNDM1Ni00NWYwLWI3OTQtM2IxNjRmYzI3MDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEzNDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYjgwYTExNTZmOTM4OTNiYTZiY2RjYTJlOGI2ODY2YTQyMzkwMzg1OWYxOTRiMTljZTc4MDcwNTcyMDQ1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v4foaAOeClkuiKtMFR1M9utu6F6n12seIrT-ByssAoI)

I misremembered, my mistake; it's an issue with Resolve on Linux in general, not specifically Wayland. Here's a thread on the Blackmagic forum about it that might help: https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=100376

**Comment by 2019Z2** [comment]
It kinda helped. I suspected it's somehow related to the monitor resolution, and there's no practical way to fix this.
And since there's no way to solve this alone, should i try the beta builds?
