### ISSUE TITLE
Is it possible to use a different Nvidia driver for davincibox?

### ISSUE THREAD

**Issue by nawka12** [zelikos/davincibox#117]
I currently have Davincibox working with RTX 2060 and Nvidia driver 560 on Host OS (Ubuntu 24.04). However, the driver broke Wayland and there's an app I wanna use that depends on Wayland.

I tried to downgrade host OS driver back to 555 where Wayland works, but then DaVinci Resolve stops working and spitting out OpenGL error.

I think it's because the distrobox OS and host OS driver mismatch?

Is there something I can do about this other than keep moving between drivers when I wanna use Resolve/Wayland?

**Comment by zelikos** [comment]
The NVIDIA driver issues should be fixed as of #121; if this issue persists after [upgrading](https://github.com/zelikos/davincibox?tab=readme-ov-file#upgrading), feel free to re-open.
