### ISSUE TITLE
How to install fonts to davincibox? And why there is no h.264 or h.265 export options?

### ISSUE THREAD

**Issue by cheungyau2022** [zelikos/davincibox#126]
First of all thank you very much for this project! I tried installing Davinci Resolve on my AMD laptop with various methods and this is the only one that gives good performance. But I have two major issues:

1. Davinci Resolve in davincibox doesn't recognize many of the fonts that the host system has. And I have no idea how to install them into the container. I need to use these fonts as they are required by clients.
2. In the deliver page I can't see any option to export in H.264 and H.265 codecs. I am using the studio version and my desktop PC with Nvidia RTX 3060 can export in those codecs without any problem. My AMD laptop has no dGPU, only a Radeon 780M iGPU, but since the timeline performance is smooth in davincibox I assume that Davinci Resolve is utilizing the iGPU already. So is it a limitation of the Linux version with AMD GPU overall?

**Comment by zelikos** [comment]
1. If you copy the fonts into your home directory, i.e. into `~/.local/share/fonts`, DaVinci Resolve will see them there.
2. Codec support is very limited in the free version, and iirc even moreso with AMD GPUs. Not something this project can change. See [this section](https://github.com/zelikos/davincibox?tab=readme-ov-file#codecs) of the README

**Comment by cheungyau2022** [comment]
Thank you so much! I did try putting them into ~/.fonts but not
~/.local/share/fonts. I will try it as soon as possible. Thank you again
for your help.

**Comment by cheungyau2022** [comment]
Sadly putting fonts in ~/.local/share/fonts doesn't seem to work. I have tried rebooting the PC but still couldn't see any of the fonts I installed. Are there any other way to add new fonts into distrobox?

**Comment by zelikos** [comment]
I tested again with a different Titles effect (Text+ instead of Text), and was able to reproduce the issue. Following the steps in this post solved it for me: https://www.reddit.com/r/blackmagicdesign/comments/nzzi2l/importing_fonts_into_davinci_resolve_with_linux/

**Comment by cheungyau2022** [comment]
> I tested again with a different Titles effect (Text+ instead of Text), and was able to reproduce the issue. Following the steps in this post solved it for me (with my fonts in ~/.local/share/fonts as described, but it could easily be altered for ~/.fonts too): https://www.reddit.com/r/blackmagicdesign/comments/nzzi2l/importing_fonts_into_davinci_resolve_with_linux/

Yes finally this works! Sadly after a few hours of testing it out I found that the performance of Davinci Resolve under Linux is sooooooooo much worse than in Windows and I have to switch back. In davincibox I can't even get a single 1080P file to playback in realtime but in Windows I can easily edit 3-4 tracks of 1080P videos with some text effects., with my AMD iGPU only.
