### ISSUE TITLE
many videos not loading or not playing

### ISSUE THREAD

**Issue by freeknot** [zelikos/davincibox#134]
I am on Resolve 19 Free Version.

I am not sure if it's a bug, a regular behavior of resolve, a license limit thing, or a codec thing of the host system, but I have the following issues:

- a regular recording from obs (mkv) does **NOT** open at all, no error nothing
- a youtube video downloaded with `yt-dlp` (mp4) **CAN** be loaded and played but has **NO** sound
- a regular mp3 file **CAN** be loaded and played and **HAS** sound
- a random video off my android **CAN** be imported, but can **NOT** be played at all, has **NO** preview image

One ore two videos not working would be ok, but this out of the box behavior with so many files not working, makes me assume, that there is something wrong or misconfigured.

**Installation method used**

- [x] `setup.sh`

**System information (please complete the following)**

 - Distro: Linux Mint 22
 - Desktop Environment: Cinnamon
 - GPU: AMD ATI Radeon RX Vega 6
 - Davincibox version: ghcr.io/zelikos/davincibox-opencl  latest

**Comment by zelikos** [comment]
https://github.com/zelikos/davincibox?tab=readme-ov-file#codecs

**Comment by freeknot** [comment]
@zelikos thanks and sorry
