### ISSUE TITLE
'cannot execute: required file not found' error when manually installing

### ISSUE THREAD

**Issue by jahinzee** [zelikos/davincibox#24]
So I decided to manually install the davincibox image using distrobox, and the installer fails with this error (this is from within the container):

```
[jahinzee@davincibox ~]$ ls
DaVinci_Resolve_18.6.1_Linux.run  [ redacted ]
DaVinci_Resolve_18.6.1_Linux.zip  [ redacted ]
[jahinzee@davincibox ~]$ setup-davinci './DaVinci_Resolve_18.6.1_Linux.run' distrobox
Extracting /home/jahinzee/DaVinci_Resolve_18.6.1_Linux.run ...
/usr/bin/setup-davinci: line 26: /home/jahinzee/DaVinci_Resolve_18.6.1_Linux.run: cannot execute: required file not found
/home/jahinzee/DaVinci_Resolve_18.6.1_Linux.run could not be extracted.
Please double-check that it is a valid DaVinci Resolve installer.
[jahinzee@davincibox ~]$
```

As seen above, the file is clearly there, but for some reason it is unable to be picked up by the system. I tried marking the file as executable but no success.

**Comment by zelikos** [comment]
This is a weird one. I can't currently reproduce it on my end:

```
📦[akzel@davincibox ~]$ ls
DaVinci_Resolve_18.6.1_Linux.run  Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
📦[akzel@davincibox ~]$ setup-davinci './DaVinci_Resolve_18.6.1_Linux.run' distrobox
Extracting /home/akzel/DaVinci_Resolve_18.6.1_Linux.run ...
# expected output follows
```

That being said, the DaVinci installer *has* given me trouble before, and 'cannot execute: required file not found' is coming from the call to `--appimage-extract`, not from the setup-davinci script.

Try re-downloading DaVinci and running setup-davinci again. Let me know if you get the error still

**Comment by gtakodev** [comment]
I have exactly the same problem here ! 

Doesn't seem to be a davincibox problem but a distrobox problem.

I tried to install DaVinci Resolve manually using distrobox but i have the same error message. For some reason the DaVinci_Resolve_18.6.1_Linux.run file ( in my case 18.6.4 ) is not found.

**Comment by lonegamedev** [comment]
Same.

Extracting also doesn't work inside the container.

Host: Arch
Guest: Fedora 37
Version of DaVinci: 18.6.4

**Comment by bdefore** [comment]
Same here!

Host: Manjaro kernel 6.6
Guest: Fedora 39
DaVinci: 18.6.5 and 18.6.4

**Comment by zelikos** [comment]
It is clear that this issue affects a number of users, but I've never been able to reproduce it myself. Neither on my main system, nor in virtual machines. My own testing has been on Fedora 38 & 39, LMDE, and elementary OS 7.x. What I'm seeing so far from the replies here is:

- Unknown OS (the OP)
- Fedora 39
- Arch Linux
- Manjaro

The guest OS would be from the davincibox container, which...has never had a Fedora 37 version, so I don't know how two of the people here could have both had Fedora 37 as the guest OS.

As for those Arch and Manjaro, I haven't tested on Arch myself, so I'll be doing so sometime today. Based on gtakodev's comment, I agree with his suspicion that it's a distrobox bug, but we'll need to do more testing to confirm.

For those who want to help with troubleshooting:

- Make sure davincibox is [on the latest version](https://github.com/zelikos/davincibox#upgrading)
- If you run into this issue on Fedora, confirm whether using toolbox instead of distrobox works or not

And provide the following information:

**Host OS**: Use NAME + VERSION from `cat /etc/os-release` (if you're on Arch, use VERSION_ID)
**Davincibox version**: The full output of `podman image list | grep davincibox`
**Distrobox version**: Get the version number from `apt show distrobox`, `dnf info distrobox`, `pacman -Si distrobox`, etc
**Terminal output**: Follow the same steps the OP showed, and paste the terminal output of doing so

**Comment by bdefore** [comment]
Great news everyone. I've worked around this issue by manually extracting the AppImage from the host beforehand (not inside distrobox). After seeing what setup-davinci does (https://github.com/zelikos/davincibox/blob/main/system_files/usr/bin/setup-davinci) I was able to manually run the relevant steps to install and successfully launch DR.

The steps I took:

From the host OS, run:
```
./DaVinci_Resolve_18.6.5_Linux.run --appimage-extract
```

If successful, you should not see the error from the OP, but rather see files being output and ultimately end up with a directory called `squashfs-root`.

Then, enter the distrobox:

```
distrobox enter YOUR_DISTROBOX_NAME
```

Now, ensure you are in the directory where you've extracted and run the relevant steps in setup-davinci. First prepare the variables from from https://github.com/zelikos/davincibox/blob/f31d81ac7fa1fdfe6a1c02a755790fd9cbc66205/system_files/usr/bin/setup-davinci#L7C1-L10C135:

```
export gdk_pixbuf_tmp_dir=/tmp/gdk-pixbuf
export fc38_gdk_pixbuf_package=gdk-pixbuf2-2.42.10-2.fc38.x86_64.rpm
export fc38_gdk_pixbuf_url=https://dl.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/Packages/g/$fc38_gdk_pixbuf_package
```

Then execute steps from https://github.com/zelikos/davincibox/blob/f31d81ac7fa1fdfe6a1c02a755790fd9cbc66205/system_files/usr/bin/setup-davinci#L35-L46.

There are `rm` actions here, take care of what you're doing!

```
# See https://github.com/zelikos/davincibox/issues/35
sudo QT_QPA_PLATFORM=minimal squashfs-root/AppRun -i -a -y
# Workaround for an issue with Resolve's included libglib-2.0
# May not be needed in the future
sudo rm /opt/resolve/libs/libglib-2.0.so /opt/resolve/libs/libglib-2.0.so.0 /opt/resolve/libs/libglib-2.0.so.0.6800.4
rm -rf squashfs-root/
# Fix for: gdk_pixbuf undefined symbol: g_task_set_static_name
# Thanks to MiMillieuh https://www.reddit.com/r/voidlinux/comments/12g71x0/comment/ju9ygqx
mkdir -p $gdk_pixbuf_tmp_dir
wget $fc38_gdk_pixbuf_url -P $gdk_pixbuf_tmp_dir
rpm2cpio $gdk_pixbuf_tmp_dir/$fc38_gdk_pixbuf_package | cpio -idmv -D $gdk_pixbuf_tmp_dir
sudo cp -r $gdk_pixbuf_tmp_dir/usr/lib64/* /opt/resolve/libs/
rm -rf $gdk_pixbuf_tmp_dir
```

Now, remain in your Distrobox, and try to run DR:

```
QT_QPA_PLATFORM=xcb /opt/resolve/bin/resolve
```

You should see the DR splash window followed by the main application.

Keep in mind my steps are for a host of Manjaro Sway (Wayland). You may encounter differences on other setups.

**Comment by bdefore** [comment]
@zelikos The ideal here would be to adapt setup-davinci to offer an option to skip the extraction step, either with another entry point, or by detection of the squashfs-root directory and skipping, or some other implementation. Then none of the above steps would be necessary.

**Comment by bdefore** [comment]
@zelikos Per your request, here is what I was running to encounter this issue:

```
→ distrobox enter davincibox -- setup-davinci /home/d4/Downloads/dr/onemore/DaVinci_Resolve_18.6.5_Linux.run distrobox
Extracting /home/d4/Downloads/dr/onemore/DaVinci_Resolve_18.6.5_Linux.run ...
/usr/bin/setup-davinci: line 30: /home/d4/Downloads/dr/onemore/DaVinci_Resolve_18.6.5_Linux.run: cannot execute: required file not found
/home/d4/Downloads/dr/onemore/DaVinci_Resolve_18.6.5_Linux.run could not be extracted.
Please double-check that it is a valid DaVinci Resolve installer.
```

And here is my system information:

```
→ yay -Si distrobox
Repository      : extra
Name            : distrobox
Version         : 1.7.0-1
Description     : Use any linux distribution inside your terminal.
Architecture    : any
URL             : https://distrobox.it/
Licenses        : GPL-3.0-only
Groups          : None
Provides        : None
Depends On      : bash
Optional Deps   : docker: Docker support
                  podman: Podman support
Conflicts With  : None
Replaces        : None
Download Size   : 113.99 KiB
Installed Size  : 403.99 KiB
Packager        : Robin Candau <[antiz@archlinux.org](mailto:antiz@archlinux.org)>
Build Date      : Thu 29 Feb 2024 05:00:36 AM EST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

```
→ podman image list | grep davincibox
[ghcr.io/zelikos/davincibox](http://ghcr.io/zelikos/davincibox)                 latest      ccaa824a2386  3 days ago    6.67 GB
```

```
→ cat -p /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

**Comment by bdefore** [comment]
> Try manually running in the container `/path/to/DaVinci_Resolve_18.6.1_Linux.run --appimage-extract` to see if the error occurs outside of setup-davinci.

@zelikos Note that when running from the Distrobox container, this still gives the `required file not found`. I was only able to extract from the host.

**Comment by zelikos** [comment]
> ```
> QT_QPA_PLATFORM=xcb /opt/resolve/bin/resolve
> ```
> 
> You should see the DR splash window followed by the main application.
> 
> Keep in mind my steps are for a host of Manjaro Sway (Wayland). You may encounter differences on other setups.

As well as your being on Sway, I'm noticing that you have `QT_QPA_PLATFORM=xcb` before launching Resolve; what happens if that's omitted? We don't currently do that in the `add-davinci-launchers` script, but if Resolve doesn't launch without it on some desktops, that's something I want to fix too

**Comment by bdefore** [comment]
Correct. Without that value, for me DR hangs with terminal output:

```
→ /opt/resolve/bin/resolve
ActCCMessage Already in Table: Code= c005, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c006, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= c007, Mode= 13, Level=  1, CmdKey= -1, Option= 0
ActCCMessage Already in Table: Code= 2282, Mode=  0, Level=  0, CmdKey= 8, Option= 0
PnlMsgActionStringAdapter Already in Table: Code= 615e, Mode=  0, Level=  0, CmdKey= -1, Option= 0
18.6.5.0007 Linux/Clang x86_64
Main thread starts: C9D2B000
0x7f17c9d2b000 | Undefined            | INFO  | 2024-03-08 14:05:34,841 | --------------------------------------------------------------------------------
0x7f17c9d2b000 | Undefined            | INFO  | 2024-03-08 14:05:34,841 | Loaded log config from /home/d4/.local/share/DaVinciResolve/configs/log-conf.xml
0x7f17c9d2b000 | Undefined            | INFO  | 2024-03-08 14:05:34,841 | --------------------------------------------------------------------------------
```

In the logfile is:

```
→ cat -p ~/.local/share/DaVinciResolve/logs/ResolveDebug.txt

*snip*
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, xcb.
*snip*
```

It's possible I'm declaring it as `wayland` in my shell scripts although a quick ripgrep doesn't spot it.

I think you'd be safe to force it to `xcb` since you're in control of the containing OS, right?

**Comment by zelikos** [comment]
So I've finally been able to reproduce this issue myself. On an Arch installation with GNOME, `setup-davinci` worked as expected. However, on Manjaro Sway, I did in fact run into the same issue reported here. So the issue may be caused the lack of a package that Sway doesn't include, but desktop environments like GNOME, KDE, Pantheon, etc do. That's assuming that the others that ran into this issue were also using Sway (maybe other tiling WMs too?)

**Comment by bdefore** [comment]
It may well be a broader issue, as I've seen it reported from folks trying to run .run files other than Davinci. I came to find davincibox after encountering the same error using Tratofin's guide here:

https://www.youtube.com/watch?v=AT3sC5VfZEs
https://gitlab.com/trafotin/os-install-scripts

**Comment by zelikos** [comment]
Yeah, my searching for any relevant info hasn't come up with anything helpful. I think moving the extraction step out of the container is probably how we'll have to work around this, like you suggested. I'll work on that today.

**Comment by bdefore** [comment]
I like that idea. Even if it requires another step in setup, it's probably better than solving this for the user.

Appreciate your work on this!

**Comment by zelikos** [comment]
The container is currently [rebuilding](https://github.com/zelikos/davincibox/actions/runs/8209868944) after #60; once it's done, those affected by this issue, please make sure davincibox is [up-to-date](https://github.com/zelikos/davincibox#upgrading), follow the new setup instructions, and re-test.
