### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by rothgar** [zelikos/davincibox#28]
I have resolve 18.6 installed in /opt and also tried this installed via distrobox and when I launch it from distrobox I don't have any sound.

All of my projects are available and if I launch them with the local installation sound works just fine.

Opening this ticket as I debug it some more and to see if I missed anything in the config.

When I play back files with audio I don't get any audio "waves" in the sound panel at all which is really weird to me. It's like it's not even trying to play audio.

**Comment by zelikos** [comment]
I suspect the cause might be a missing package I'd need to add to the container, but I'm not sure what it'd be

What file format(s) are the files you're using? i.e. what container, what audio codec?

I'm getting audio playback on my end, but my clips are all using PCM (since that's one of few that work in the free version). The waveforms do sometimes take a little while to load, but they do load

**Comment by rothgar** [comment]
I tried with a couple different files. Here's the `ffprobe` output. Both are .mov containers (that's all that usually works for me.

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'carbonyl.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf60.3.100
  Duration: 00:02:31.28, start: 0.000000, bitrate: 46713 kb/s
  Stream #0:0[0x1]: Video: dnxhd (DNXHD) (AVdn / 0x6E645641), yuv422p(tv, bt709), 1920x1080, 45174 kb/s, SAR 607:1920 DAR 607:1080, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : FFMP
      encoder         : Lavc60.3.100 dnxhd
  Stream #0:1[0x2]: Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../fork-it/01/fork-it-01.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf60.3.100
  Duration: 00:13:31.94, start: 0.000000, bitrate: 46716 kb/s
  Stream #0:0[0x1]: Video: dnxhd (DNXHD) (AVdn / 0x6E645641), yuv422p(tv, bt709), 1920x1080, 45174 kb/s, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 30k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : FFMP
      encoder         : Lavc60.3.100 dnxhd
  Stream #0:1[0x2]: Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

**Comment by zelikos** [comment]
Yeah that is strange, then. Those are basically the same as what I've used in Resolve, too, but audio is playing back for me.

If you check the 'About' option under 'DaVinci Resolve' in the menu, what specific version and build number are you on?
![Screenshot from 2023-10-11 01-47-21](https://github.com/zelikos/davincibox/assets/26857149/7a967c92-a7a3-4a88-9988-d34f2ccc3d60)

**Comment by rothgar** [comment]
I'm on studio 18.6 build 9
https://github.com/zelikos/davincibox/issues/26#issuecomment-1755899415

**Comment by zelikos** [comment]
Very weird.

Just to confirm, your Audio settings between the local install and the davincibox install are the same, correct?
![Screenshot from 2023-10-11 12-10-40](https://github.com/zelikos/davincibox/assets/26857149/49146029-f260-4b5a-830a-cf6659290334)

**Comment by rothgar** [comment]
I didn't check that before but I just did and they're both set up the some (automatic speaker config) I tried manually adjusting it and selecting different ALSA devices but still no sound.

**Comment by zelikos** [comment]
Can you do a test with the free version, too? I'm wondering if this affects both versions, or somehow just the Studio version. If it only affects Studio, it'll be much harder for me to troubleshoot, unfortunately

**Comment by rothgar** [comment]
I just tried with a new distrobox container with non-studio davinci

```
distrobox create -i ghcr.io/zelikos/davincibox:latest -n davincibox2
distrobox enter davincibox2 -- setup-davinci ~/Downloads/DaVinci_Resolve_18.6.2_Linux.run distrobox
distrobox enter davincibox2 -- /opt/resolve/bin/resolve
```
And verified I don't have sound with the non-studio version

I Installed vlc and tested a video file and I do have audio
```
distrobox enter davincibox -- sudo dnf install vlc
distrobox enter davincibox -- vlc
```

**Comment by trevnels** [comment]
I was seeing this same behavior, though I was able to get audio working in Resolve by running `sudo dnf install pipewire-pulseaudio pipewire-alsa` inside the distrobox. Not sure if both are required, since it looks like Resolve just uses ALSA.
