### ISSUE TITLE
Create desktop launcher manually

### ISSUE THREAD

**Issue by zelikos** [zelikos/davincibox#3]
If we do it with distrobox-export, the resulting file requires that /opt/resolve exists on the host. Right now this is worked around by running `pkexec mkdir /opt/resolve`, but that requires admin priveleges, which isn't ideal

**Comment by bluesabre** [comment]
If you remove the `Path=` line from the resulting launcher, that will allow it to operate. I also had to copy the launcher icon to the host and update the `Icon=` line. Here's my resulting `~/.local/share/applications/davincibox-com.blackmagicdesign.resolve.desktop`:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=DaVinci Resolve  (on davincibox)
GenericName=DaVinci Resolve  (on davincibox)
Comment=Revolutionary new tools for editing, visual effects, color correction and professional audio post production, all in a single application!
Exec=/usr/bin/distrobox-enter  -n davincibox --   /opt/resolve/bin/resolve  %u
Terminal=false
MimeType=application/x-resolveproj;
Icon=/var/home/bluesabre/.local/share/davincibox/DV_Resolve.png
StartupNotify=true
Name[en_US]=DaVinci Resolve  (on davincibox)
StartupWMClass=DaVinci Resolve
```

(Not sure if this helps at all)
