### ISSUE TITLE
it just won't install

### ISSUE THREAD

**Issue by theonekingboo** [zelikos/davincibox#47]
sorry but it just won't let me install it says:
Authorization required, but no authorization protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

/tmp/.mount_DaVincDP2Chq/AppRun: line 347: 141290 Aborted                 (core dumped) "${CURRENT_DIR}/installer" "${CURRENT_DIR}" "$@"

**Comment by zelikos** [comment]
What distro are you using?

**Comment by theonekingboo** [comment]
> What distro are you using?

Linux mint victoria

**Comment by zelikos** [comment]
Run `podman image list | grep davincibox` and paste the output here

**Comment by theonekingboo** [comment]
@zelikos 
$ podman image list | grep davincibox
ghcr.io/zelikos/davincibox                 latest      790a88c74e03  2 months ago  4.91 GB

**Comment by zelikos** [comment]
You have an older version of davincibox from before [this issue](https://github.com/zelikos/davincibox/issues/35) was fixed. Follow the [upgrading](https://github.com/zelikos/davincibox#upgrading) steps in the README, then let me know if the issue persists.

**Comment by theonekingboo** [comment]
alright thanks

**Comment by theonekingboo** [comment]
yep it worked thanks
