### ISSUE TITLE
Could I somehow modify the script for it to force wayland on Davinci?

### ISSUE THREAD

**Issue by tuandatdavid** [zelikos/davincibox#70]
I heard Davinci Resolve 19 supports wayland and it was bothering my head for a while.
(bruh I am reading what I just wrote and it seems like it's a troll post, but I am serious).
Answers would be appreciated

**Comment by zelikos** [comment]
You would want to modify `/usr/bin/run-davinci` inside the container, and change `QT_QPA_PLATFORM=xcb` to `QT_QPA_PLATFORM=wayland`. DaVinci Resolve 19 is still in beta, though, so I'm not testing nor supporting davincibox against it until the stable release happens.

Closing this as it's a non-actionable issue.
