### ISSUE TITLE
rusticl testing

### ISSUE THREAD

**Issue by zelikos** [zelikos/davincibox#72]
mesa-libOpenCL was added to davincibox as of #67 and so rusticl is now available as an [opt-in option for testing](https://github.com/zelikos/davincibox?tab=readme-ov-file#amd).

ROCm has given me plenty of issues in the past and recently. As of Mesa 24.1.1, rusticl seems to handle DaVinci Resolve fine on my system (though it doesn't handle Fusion too well).

**I want to evaluate making rusticl the default for AMD ~~& Intel users~~**, but I need wider testing than just my own results.

## Testers, please check the following:

**Run DaVinci Resolve with:**  
Distrobox: distrobox enter -n davincibox -- /usr/bin/run-davinci rusticl
Toolbox: toolbox run -c davincibox /usr/bin/run-davinci rusticl

**Nvidia**  
Check whether running with the above command prevents using Resolve with CUDA as normal

**Intel**  
Davincibox ships the `intel-compute-runtime` for Intel GPUs. Follow the same testing steps as the AMD section below to test rusticl on Intel.

**AMD**  
Compare your experience with ROCm (the current default) to your experience with using rusticl. Note that when switching between the two, you may get a popup about needing to update your GPU configuration, and sometimes the switch may not seem to work at first. Just re-launch Resolve if the latter case happens.

Please report any notable differences in DaVinci Resolve usage that you think are relevant.

Some examples, including but not limited to:
- Timeline performance, especially with VFX added
- Rendering performance
- Any differences in app stability

**Comment by user7z** [comment]
in my intel platform it was unusable , but after adding the rusticl it run properly without gpu pop up panel.
i did not test further to see GPU usage etc ... , plz if needed give me a relevent informations "guide" to share the results of the intel platform

**Comment by zelikos** [comment]
As `rusticl` is now the default for AMD GPUs and `intel-compute-runtime` seems to work for Intel, I'm closing this issue in favor of more specific issue reports in the future.
