### ISSUE TITLE
Gpu initialization failed

### ISSUE THREAD

**Issue by Majoramari** [zelikos/davincibox#83]
**IMPORTANT**

Before reporting a bug, make sure that you can reproduce it on the latest version of davincibox.

See the [upgrading](https://github.com/zelikos/davincibox#upgrading) section of the README for more information.

**Describe the bug**

Error on welcome screen "Gpu initialization failed"

**Installation method used**

- [x] `setup.sh`
- [x] Manual
  - [x] Distrobox
  - [ ] Toolbox

**To Reproduce**

Just run the application

**Expected behavior**
It should run normally

**Screenshots**
![image](https://github.com/zelikos/davincibox/assets/33487552/f05c6207-fa4f-4c1e-b263-e396ce8f5353)

**System information (please complete the following)**

 - Distro: openSUSE tumbleweed, endeavourOS
 - Desktop Environment: KDE plasma 6.0.5 (Wayland and X11)
 - GPU: NVIDIA RTX 3060 - 550 drivers

**Additional context**
I tried to install it out of distrobox and its working so its something with the script in my opinion!

- I have NVIDIA Container Toolkit installed

**Comment by zelikos** [comment]
Run the following:
`distrobox enter davincibox -- sudo dnf update`

and let me know if the issue persists. The last build is from 6 days ago, so it might be that the drivers in the container need updating.

**Comment by Majoramari** [comment]
> Run the following: `distrobox enter davincibox -- sudo dnf update`
> 
> and let me know if the issue persists. The last build is from 6 days ago, so it might be that the drivers in the container need updating.

I used the command you provide and same issue

Notes:
- I switch my host driver: 555 beta
- I tried this [script](https://github.com/VortexAcherontic/shell_scripts/blob/main/distrobox/davinci_resolve/distrobox-nvidia.ini) and its working fine!

**Comment by zelikos** [comment]
Try recreating the container through the [Manual setup](https://github.com/zelikos/davincibox#manual) process, but on the `distrobox create` step, append `--nvidia` to the command, i.e. `distrobox create -i ghcr.io/zelikos/davincibox:latest -n davincibox --nvidia`. Follow the rest of the steps as normal.

**Comment by Majoramari** [comment]
> distrobox create -i ghcr.io/zelikos/davincibox:latest -n davincibox --nvidia

Okay I used this command `distrobox create -i ghcr.io/zelikos/davincibox:latest -n davincibox --nvidia` and tried to update the system `sudo dnf update` then installed davinci `sudo ./DaVinci_Resolve_18.6.6_Linux.run`...

I got this error:
```
Please install the following missing packages:
    zlib

Use SKIP_PACKAGE_CHECK=1 to bypass the system package check.
```

so I skipped the check `sudo SKIP_PACKAGE_CHECK=1 ./DaVinci_Resolve_18.6.6_Linux.run`

Now all set I should be able to run Davinci using `/opt/resolve/bin/resolve` but I get this error `/opt/resolve/bin/resolve: symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer`

**Comment by zelikos** [comment]
> then installed davinci `sudo ./DaVinci_Resolve_18.6.6_Linux.run`...

If you ran `sudo ./DaVinci_Resolve_18.6.6_Linux.run`, you didn't follow the [instructions in the README](https://github.com/zelikos/davincibox#manual).

**Comment by Majoramari** [comment]
> > then installed davinci `sudo ./DaVinci_Resolve_18.6.6_Linux.run`...
> 
> If you ran `sudo ./DaVinci_Resolve_18.6.6_Linux.run`, you didn't follow the [instructions in the README](https://github.com/zelikos/davincibox#manual) that I linked previously.

Sorry! now I re done it, wit following the manual instructions provided:

create the bottle using this command
`distrobox create -i ghcr.io/zelikos/davincibox:latest -n davincibox --nvidia`

Extracting the files using `./DaVinci_Resolve_18.6.6_Linux.run --appimage-extract` and now setup davinci using `distrobox enter davincibox -- setup-davinci squashfs-root/AppRun distrobox` and just incase! update the system using `distrobox enter davincibox -- sudo dnf update`

Note: I didn't add an app icon!

Running davnci using: `distrobox enter davincibox -- /opt/resolve/bin/resolve`
Same error: 
`/opt/resolve/bin/resolve: symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer`

**Comment by zelikos** [comment]
Try running with `distrobox enter davincibox -- /usr/bin/run-davinci`

**Comment by Majoramari** [comment]
> Try running with `distrobox enter davincibox -- /usr/bin/run-davinci`

Yeah it worked fine!
