### ISSUE TITLE
New setup.sh file is unable to use .run installer

### ISSUE THREAD

**Issue by ItsRogueRen** [zelikos/davincibox#91]
Cannot extract the .run file on latest setup.sh file in Releases (as of 06-20-2024). Error states that it cannot determine if the .run is a valid installer for Resolve despite the same file working for previous releases. 

**Installation method used**

- [ x] `setup.sh`
- Manual
  - [ ] Distrobox
  - [ ] Toolbox

**To Reproduce**

1. Go to Releases
2. Download the latest version 1.2.0
3. Follow the instructions for running setup.sh

**Expected behavior**

.run file to be extracted and install Resolve within a Davincibox

**System information (please complete the following)**

 - Distro: Nobara 40 (Fedora based)
 - Desktop Environment: KDE Plasma Wayland
 - GPU: AMD Radeon RX 7700 XT

**Additional context**
Can be worked around by using 1.1.0 and then upgrading.

**Comment by zelikos** [comment]
Latest setup.sh did successfully extract the .run installer for me (though I have a separate, non-breaking error I need to troubleshoot now...)

Copy-paste the full terminal output from your attempt

**Comment by ItsRogueRen** [comment]
> Latest setup.sh did successfully extract the .run installer for me (though I have a separate, non-breaking error I need to troubleshoot now...)
> 
> Copy-paste the full terminal output from your attempt

I just shut down my PC for the night, I'll edit this in the morning with the output

**Comment by zelikos** [comment]
Looks like the issue was an oversight from #88. Should be fixed now in 1.3.0

If the issue persists with the updated script, please reopen this issue.
