### ISSUE TITLE
Issues with Nvidia GPU integration on Linux Mint

### ISSUE THREAD

**Issue by zelikos** [zelikos/davincibox#96]
See https://github.com/zelikos/davincibox/issues/76#issuecomment-2184198966 from @lolgufdHD

**Comment by GravermanDev** [comment]
I have the same problem on Linux Mint. I also tested normal installation and got a similar output to https://github.com/zelikos/davincibox/issues/76#issuecomment-2184182846

**Comment by HimangsKalita** [comment]
I can confirm the issue  Nvidia GTX 1650 running on Linux Mint
![image](https://github.com/zelikos/davincibox/assets/51876341/f33f21d4-9cb8-44fd-bfbf-ad2b607f7fe9)

**Comment by polvallverdu** [comment]
Having same issue here with Linux Mint 22, and a 3070
![image](https://github.com/user-attachments/assets/ec57999b-7b45-4a8c-9ea1-dcc929bb4214)

**Comment by Burgerpower01** [comment]
I was able to get DaVinci 18.6.6 (Studio) running by removing `akmod-nvidia` and `xorg-x11-drv-nvidia-cuda` from the `extra-packages` file and building the container image myself. 

My driver version in Mint 22 and the davincibox container are now both 535.183.01. But I don't know if this will break with a driver update...

Also, `glxinfo -B` doesn't show an error anymore.

**Comment by zelikos** [comment]
The NVIDIA driver issues should be fixed as of #121; if this issue persists after [upgrading](https://github.com/zelikos/davincibox?tab=readme-ov-file#upgrading), feel free to re-open.
