### ISSUE TITLE
Control panels not working

### ISSUE THREAD

**Issue by rothgar** [zelikos/davincibox#98]
**IMPORTANT**

Before reporting a bug, make sure that you can reproduce it on the latest version of davincibox.

See the [upgrading](https://github.com/zelikos/davincibox#upgrading) section of the README for more information.

**Describe the bug**

I just did a fresh install of 18.6.6 studio version and opened davinci and went to the control panel setup and my speed editor is not detected. I manually launched `/opt/resolve/DaVinci Control Panels Setup/DaVinci Control Panels Setup` and the panel is found in that window but when I click on it to perform a firmware update it fails.

The logs at the console say
```
/opt/resolve/DaVinci Control Panels Setup 
$ ./DaVinci\ Control\ Panels\ Setup 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
*** WARNING *** The program 'DaVinci Control Panels Setup' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=DaVinci Control Panels Setup>
DFU Upgrade: Getting device info.
DFU Upgrade: Waiting for initial arrival.
DFU Upgrade: Current boot mode  255
DFU Upgrade failure:  Failed to get DFU interface before detach
```
And the GUI window says 
![image](https://github.com/zelikos/davincibox/assets/371796/89e2d321-bed7-4873-87af-2eb114948ef0)

**Installation method used**

- [ ] `setup.sh`
- [x] Manual
  - [x] Distrobox
  - [ ] Toolbox

**To Reproduce**

1. install davinci
2. launch control panel setup from CLI
3. Updates and panels should work

**Expected behavior**

Control panels should work

**Screenshots**

**System information (please complete the following)**

 - Distro: Bluefin
 - Desktop Environment: GNOME
 - GPU: Nvidia GTX 1070 with 555.58 driver

**Additional context**
Has anyone seen this error or know steps to get the speed editor to work?

**Comment by rothgar** [comment]
I also had to remove a couple of the built in davinci libraries to get it to run. I was getting errors with libgio so I found this on reddit and it worked for me.

```
cd /opt/resolve/libs
sudo mkdir disabled-libraries
sudo mv libglib* disabled-libraries
sudo mv libgio* disabled-libraries
sudo mv libgmodule* disabled-libraries
```

**Comment by zelikos** [comment]
I don't have any of the DaVinci Resolve related hardware to test with myself, so I'm unable to directly troubleshoot this, unfortunately.

> I also had to remove a couple of the built in davinci libraries to get it to run.

To clarify: does "it" here refer specifically to the Control Panels Setup? Not DaVinci Resolve?

**Comment by rothgar** [comment]
Correct. The control panels setup was the problem.

However, I went and tested this outside of davincibox and I had the same problem so this isn't a problem specifically with davincibox and instead something on my system (or davinci on Linux in general). I'm going to close this issue since I don't think there will be a solution here.

Thanks

**Comment by zelikos** [comment]
> Correct. The control panels setup was the problem.

OK yeah, that makes sense, then. The workaround we have right now for the built-in libraries only applies to running DaVinci Resolve itself; I'll open a separate issue about accounting for the other things Resolve comes with too.
