### ISSUE TITLE
`internal libpod error` in Linux Mint

### ISSUE THREAD

**Issue by HimangsKalita** [zelikos/davincibox#99]
**Describe the bug**

I am following the manual method of installation, everything works fine until this command 

```
distrobox enter davincibox -- setup-davinci squashfs-root/AppRun distrobox 
```
First error is 'command not found' in /tmp/SWqyPY.sh

![image](https://github.com/zelikos/davincibox/assets/51876341/020ae824-207c-4876-80f2-771e4b0aeafb)

The second error is Failed to write 'change' to: Permission denied 

![image](https://github.com/zelikos/davincibox/assets/51876341/9585b9fb-dda6-4d57-af9a-0c59a4bd96c7)

Here is the full output file from the terminal
[output.txt](https://github.com/user-attachments/files/16105043/output.txt)

**Installation method used**

- [ ] `setup.sh`
- Manual
  - [x] Distrobox
  - [ ] Toolbox

**To Reproduce**

1. Follow the manual method of davincibox installation until 'On the host, run --appimage-extract on your DaVinci Resolve installer'

2. Then run this command 'distrobox enter davincibox -- setup-davinci squashfs-root/AppRun distrobox'
3. See error in the terminal 

**Expected behavior**

This is my first time using Distrobox, I expected no error installing DaVinci Resolve in davincibox

**System information (please complete the following)**

 - Distro: Linux Mint virginia 21.3 x86_64
 - Desktop Environment: Cinnamon 6.0.4
 - GPU: GPU 1: NVIDIA GeForce GTX 1650 Mobile / ]
            GPU 2: Intel UHD Graphics 630 @ 1.05 GHz]

**Comment by zelikos** [comment]
Both errors listed are normal and occur even for successful installations. The point of interest is instead the `internal libpod error` at the end of your full log

**Comment by HimangsKalita** [comment]
I deleted davincibox, reinstalled distrobox and downloaded DaVinci Resolve again, restarted the system.

Again followed the manual installation method, this time Davinic Resolved was installed but new error was shown 'Segmentation fault'

![image](https://github.com/zelikos/davincibox/assets/51876341/2398434a-f47a-4479-be24-33706f6165c0)

**Comment by zelikos** [comment]
Then this is probably the same problem as #76

**Comment by HimangsKalita** [comment]
The 'Segmentation fault' issue was resolved by simply adding sudo in desktop shortcut 
![image](https://github.com/zelikos/davincibox/assets/51876341/b52de1dd-58b0-4883-8eae-cec3710afabf)

But new issue has arise 'GPU initialization failed'
![image](https://github.com/zelikos/davincibox/assets/51876341/a550d943-44d0-4039-8ee6-5fc1f67c7c6d)

Here is host machine nvidia-smi 
![image](https://github.com/zelikos/davincibox/assets/51876341/3a2d53b3-9d84-4ecc-87e7-e17807e3f947)

Here is davincibox nivida-smi 
![image](https://github.com/zelikos/davincibox/assets/51876341/c8e80a48-b137-4ba0-9e79-aa159b7adbb4)
